export { AboutHero } from './about-hero'
export { AboutOverview } from './about-overview'
export { AboutSection as AboutContent } from './about-content'
export { AboutSteps } from './about-steps'
export { AboutProcess } from './about-process'
export { AboutRoadmap } from './about-roadmap'
export { AboutFeatures } from './about-features'
export { AboutTeam } from './about-team'
export { AboutGallery } from './about-gallery'
export { AboutVideo } from './about-video'
export { AboutCTA } from './about-cta'